### ISSUE TITLE
Compile package/kernel/mac80211 will failed

### ISSUE THREAD

**Issue by panda-mute** [MarvellEmbeddedProcessors/openwrt-dd#1]
I try to compile 8040DB with mwlwifi (change depends to mvebu64), and choose kernel to opewrt-kernel(17.02 release), the package/kernel/mac80211 will failed (not compile mac80211.ko), can you help to take a look?

**Comment by panda-mute** [comment]
Why not use package/kernel/mac8011 directly, I have fix compile issue and make sure it is work.
kernel:
https://github.com/marvell-wireless/openwrt-kernel
openwrt:
https://github.com/marvell-wireless/openwrt

This will make future migrate to latest openwrt more easy!

**Comment by damirsamardzic** [comment]
I'm sorry for the late response, I have retested with the current 17.02 release branches and mwlwifi builds fine. The issue seem to be solved in recent commits.
