### ISSUE TITLE
Makefile for lede_17.06_release is referencing DTS files that are missing

### ISSUE THREAD

**Issue by ttocsr** [MarvellEmbeddedProcessors/openwrt-dd#10]
https://github.com/MarvellEmbeddedProcessors/openwrt-dd/blob/lede_17.06_release/target/linux/mvebu64/image/Makefile

`# Marvell Armada 3720 Development Board DB-88F3720-DDR3`
`define Image/BuildKernel/Profile/armada-3720-db`
`	cp $(KDIR)/Image $(BIN_DIR)/openwrt-armada-3720-db-Image`
`	cp $(KDIR)/Image.gz $(BIN_DIR)/openwrt-armada-3720-db-Image.gz`
`	cp $(DTS_DIR)/marvell/armada-3720-db-sfp.dtb $(BIN_DIR)/armada-3720-db-sfp.dtb`
`ifeq ($(CONFIG_TARGET_ROOTFS_INITRAMFS),y)`
`	cp $(KDIR)/Image-initramfs $(BIN_DIR)/openwrt-armada-3720-db-Image-initramfs`
`endif`
`endef`

armada-3720-db-sfp.dts does not exist in lede_17.06 openwrt-kernel branch. 
The Makefile and dts files should be updated for the lede_17.06 custom kernel
https://github.com/MarvellEmbeddedProcessors/openwrt-kernel/blob/lede_17.06_release/arch/arm64/boot/dts/marvell/Makefile

**Comment by v-vid** [comment]
Hi @ttocsr,

DTB fix has been tested and pushed in the repo: https://github.com/MarvellEmbeddedProcessors/openwrt-dd/commit/8c58c310478967fdb01ee1ae9752a31f7d752098

Closing the issue.
