### ISSUE TITLE
ubuntu install

### ISSUE THREAD

**Issue by ranshalit** [MarvellEmbeddedProcessors/openwrt-dd#18]
Hello,
Is there a way to install ubuntu on armada 7x ?
Thanks

**Comment by damirsamardzic** [comment]
Hi,

you can use MACCHIATObin wiki as guideline:
http://wiki.macchiatobin.net/tiki-index.php?page=BSP+HowTo

There is information how to build kernel and prepare Ubuntu filesystem and SD card. Just pay attention that you use correct dtb file for your 7k board.
