### ISSUE TITLE
kernel 4.4.8 patch fail for espressobin profile

### ISSUE THREAD

**Issue by averyling82** [MarvellEmbeddedProcessors/openwrt-dd#2]
l_drop.patch using plaintext: 
patching file include/uapi/linux/pkt_sched.h
patching file net/sched/sch_fq_codel.c
Hunk #4 FAILED at 181.
Hunk #5 FAILED at 217.
Hunk #6 succeeded at 331 (offset -5 lines).
Hunk #7 succeeded at 383 (offset -5 lines).
Hunk #8 succeeded at 429 (offset -7 lines).
Hunk #9 succeeded at 487 (offset -7 lines).
2 out of 9 hunks FAILED -- saving rejects to file net/sched/sch_fq_codel.c.rej
Patch failed!  Please fix /home/avey/work/avery/espress/openwrt/openwrt-dd/target/linux/generic/patches-4.4/032-fq_codel-add-batch-ability-to-fq_codel_drop.patch!
make[3]: *** [/home/avey/work/avery/espress/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/.prepared] Error 1
make[3]: Leaving directory `/home/avey/work/avery/espress/openwrt/openwrt-dd/toolchain/kernel-headers'
make[2]: *** [toolchain/kernel-headers/prepare] Error 2
make[2]: Leaving directory `/home/avey/work/avery/espress/openwrt/openwrt-dd'

**Comment by v-vid** [comment]
Hi averyling82,

It seems that you're trying to build the image with the generic kernel. The current OpenWrt distribution is modified to work with the Marvell's LSP kernel which provides improvements and modifications over the generic kernel.

Please try to build the image per instructions here:
https://github.com/MarvellEmbeddedProcessors/openwrt-dd/wiki/ESPRESSObin

and put any additional patches in the _target/linux/mvebu64/patches-4.4_ directory instead.

**Comment by averyling82** [comment]
thanks a lot，I will follow the wiki.
