### ISSUE TITLE
Unable to compile openwrt-dd 17.02 release

### ISSUE THREAD

**Issue by fishy-chips** [MarvellEmbeddedProcessors/openwrt-dd#3]
Hi,
 I followed the directions from the expressobin wiki to pull down the kernel, openwrt 17.02 release, update the packages via the feeds, and perform menuconfig.

When I attempt to compile, I receive a compilation error indicating that it cannot find the Makefile located here:
/home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/host/bin/sed: can't read /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/Makefile: No such file or directory
Makefile:100: recipe for target '/home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/.prepared' failed

What step did I miss? 
Are others successful in compiling 17.02?

When I look at the reason why, it appears that linux-4.4.8 has a cyclic link with itself:drwxr-xr-x  3 buddy buddy 4096 Jun  1 14:29 .
drwxr-xr-x  4 buddy buddy 4096 Jun  1 11:59 ..
lrwxrwxrwx  1 buddy buddy   11 Jun  1 14:29 linux-4.4.8 -> linux-4.4.8
drwxr-xr-x 25 buddy buddy 4096 Jun  1 11:41 openwrt-kernel

any assistance appreciated. Thanks!

full output here:
buddy@buddy-VirtualBox ~/Projects/espresso/openwrt/openwrt-dd $ make -j1 V=s
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
make[1]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd'
make[2]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd'
+ mkdir -p /home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16
+ cd /home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16
+ mkdir -p bin lib include stamp
mkdir -p /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/stamp
touch /home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/.prepared
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Nothing to be done for 'prepare'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/binutils'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Nothing to be done for 'prepare'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/gcc/minimal'
make[3]: Entering directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/kernel-headers'
mkdir -p /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16
if [ -d /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8 ]; then rmdir /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8; fi
ln -s "/home/buddy/Projects/espresso/kernel" /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8
ln -sf linux-4.4.8 /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux
/home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/host/bin/sed -i -e 's/@expr length/@-expr length/' /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/Makefile
/home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/host/bin/sed: can't read /home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/Makefile: No such file or directory
Makefile:100: recipe for target '/home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/.prepared' failed
make[3]: *** [/home/buddy/Projects/espresso/openwrt/openwrt-dd/build_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/linux-4.4.8/.prepared] Error 2
make[3]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd/toolchain/kernel-headers'
toolchain/Makefile:81: recipe for target 'toolchain/kernel-headers/prepare' failed
make[2]: *** [toolchain/kernel-headers/prepare] Error 2
make[2]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd'
toolchain/Makefile:80: recipe for target '/home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/stamp/.toolchain_install' failed
make[1]: *** [/home/buddy/Projects/espresso/openwrt/openwrt-dd/staging_dir/toolchain-aarch64_cortex-a53+neon-vfpv4_gcc-5.3.0_musl-1.1.16/stamp/.toolchain_install] Error 2
make[1]: Leaving directory '/home/buddy/Projects/espresso/openwrt/openwrt-dd'
/home/buddy/Projects/espresso/openwrt/openwrt-dd/include/toplevel.mk:192: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by fishy-chips** [comment]
This is foolish.

I walked away after trying to figure out what went wrong. Came back and started from scratch again and noticed that I had the wrong path in the kernel path under menuconfig.

Once I fixed that, all is well.  Thanks for the support!

**Comment by Cathgao** [comment]
> This is foolish.
> 
> I walked away after trying to figure out what went wrong. Came back and started from scratch again and noticed that I had the wrong path in the kernel path under menuconfig.
> 
> Once I fixed that, all is well. Thanks for the support!

How could you solved the problem of "staging_dir/host/bin/sed:not found"?
