### ISSUE TITLE
build issue when enabing BT feature

### ISSUE THREAD

**Issue by lliangmvrl** [MarvellEmbeddedProcessors/openwrt-dd#4]
Got below build error after kmod-bluetooth is selected.
=====================================================================================================================================================================
SHELL= flock /opt/openwrt/openwrt-dd/tmp/.root-copy.flock -c 'cp -fpR /opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/root-mvebu64/tmp-kmod-nls-base/.
/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/root-mvebu64/'
rm -rf /opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/root-mvebu64/tmp-kmod-nls-base
touch /opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/root-mvebu64/stamp/.kmod-nls-base_installed
NOTICE: module '/opt/openwrt/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/linux-4.4.8/fs/nls/nls_base.ko' is built-in.
if [ -f /opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/pkginfo/linux.default.install.clean ]; then rm -f
/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/pkginfo/linux.default.install
/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/pkginfo/linux.default.install.clean; fi; echo "kmod-nls-base" >>
/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/pkginfo/linux.default.install
**ERROR: module '/opt/openwrt/openwrt-dd/build_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/linux-mvebu64/linux-4.4.8/drivers/base/regmap/regmap-core.ko' is missing.**
modules/other.mk:735: recipe for target '/opt/openwrt/openwrt-dd/bin/mvebu64/packages/kernel/kmod-regmap_4.4.8-1_mvebu64.ipk' failed
make[3]: *** [/opt/openwrt/openwrt-dd/bin/mvebu64/packages/kernel/kmod-regmap_4.4.8-1_mvebu64.ipk] Error 1
make[3]: Leaving directory '/opt/openwrt/openwrt-dd/package/kernel/linux'
package/Makefile:196: recipe for target 'package/kernel/linux/compile' failed
make[2]: *** [package/kernel/linux/compile] Error 2
make[2]: Leaving directory '/opt/openwrt/openwrt-dd'
package/Makefile:193: recipe for target '/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/opt/openwrt/openwrt-dd/staging_dir/target-aarch64_cortex-a53+neon-vfpv4_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/opt/openwrt/openwrt-dd'
/opt/openwrt/openwrt-dd/include/toplevel.mk:192: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by damirsamardzic** [comment]
I can not reproduce the issue, it seems to be solved in this openwrt-kernel commit:
https://github.com/MarvellEmbeddedProcessors/openwrt-kernel/commit/546ca8d62db529b079cd04e27876b84b1e7d43d2

Please retest with the latest 17.02 release sources.

**Comment by damirsamardzic** [comment]
The issue is still present in OpenWrt 17.06 release. I created 2 PRs to fix it:
https://github.com/MarvellEmbeddedProcessors/openwrt-kernel/pull/6
https://github.com/MarvellEmbeddedProcessors/openwrt-dd/pull/11
