### ISSUE TITLE
openvswitch: Python urllib3 ImportError: No module named urllib3

### ISSUE THREAD

**Issue by ttocsr** [MarvellEmbeddedProcessors/openwrt-dd#7]
When I compile openwrt with openvswitch, i get the following error.
ImportError: No module named urllib3

Applying this PR resolves the issue
https://github.com/openwrt/openwrt/pull/508

**Comment by damirsamardzic** [comment]
Thanks, @ttocsr!
I have created PR #8 for that issue.

**Comment by v-vid** [comment]
Merged PR for 17.02 and 17.06 branches, closing the issue.
